[package]
name = "cargonode"
version = "0.1.3"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils"
]
keywords = ["productivity", "developer-tools", "cross-platform"]
description = "A unified CLI tool that brings Cargo's developer experience to Node.js"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xosnrdev/cargonode"
homepage = "https://github.com/xosnrdev/cargonode?tab=readme-ov-file#readme"

[dependencies]
anstream = "0.6.18"
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive", "wrap_help"] }
clap-cargo = "0.15.2"
console = "0.15.10"
dirs = "6.0.0"
env_logger = "0.11.6"
indicatif = "0.17.11"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
which = "7.0.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = 'abort'
strip = true
debug = false
incremental = false
overflow-checks = false

[profile.bench]
inherits = "release"
debug = true
strip = false

[profile.dev]
opt-level = 0
debug = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.16.0"

[package.metadata.wix]
upgrade-guid = "B753834A-440E-42E6-A3B5-D5C5DCDE0BF0"
path-guid = "7B2FC1F5-FF2E-45F3-A62B-C35866B43452"
license = false
eula = false
