[workspace]
members = ["crates/cn-core"]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils"
]
keywords = ["productivity", "developer-tools", "cross-platform"]
description = "A unified CLI tool that brings Cargo's developer experience to Node.js"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xosnrdev/cargonode"
homepage = "https://github.com/xosnrdev/cargonode?tab=readme-ov-file#readme"

[workspace.dependencies]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = 'abort'
strip = true
debug = false
incremental = false
overflow-checks = false

[profile.bench]
inherits = "release"
debug = true
strip = false

[profile.dev]
opt-level = 0
debug = true
