[package]
name = "cargonode"
version = "0.1.3"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils"
]
keywords = ["productivity", "developer-tools", "cross-platform"]
description = "A unified CLI tool that brings Cargo's developer experience to Node.js"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xosnrdev/cargonode"
homepage = "https://github.com/xosnrdev/cargonode?tab=readme-ov-file#readme"

[[bin]]
name = "cargonode"
path = "src/bin/cargonode.rs"

[dependencies]
anstream = "0.6.18"
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive", "wrap_help"] }
clap-cargo = "0.15.2"
env_logger = "0.11.6"
flate2 = "1.0.35"
log = "0.4.25"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sha2 = "0.10.8"
tar = "0.4.43"
which = "7.0.2"

[build-dependencies]
flate2 = "1.0.35"
sha2 = "0.10.8"
tar = "0.4.43"

[profile.release]
debug = 1

[profile.release-lto]
inherits = "release"
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
tempfile = "3.16.0"
trycmd = "0.15.8"

[package.metadata.wix]
upgrade-guid = "B753834A-440E-42E6-A3B5-D5C5DCDE0BF0"
path-guid = "7B2FC1F5-FF2E-45F3-A62B-C35866B43452"
license = false
eula = false
