[package]
name = "cargonode"
version = "0.1.2"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
keywords = ["productivity", "developer-tools", "cross-platform"]
description = """
Unified tooling for Node.js.
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/xosnrdev/cargonode"

[[bin]]
name = "cargonode"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
fs_extra = "1.3.0"
serde = { version = "1.0.216", features = ["derive"] }
tempfile = "3.14.0"
toml = "0.8.19"
ureq = "2.12.1"
zip-extract = "0.2.1"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies]
jemallocator = "0.5.4"

[profile.release]
debug = 1

[profile.release-lto]
inherits = "release"
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

# This is the main way to strip binaries in the deb package created by
# 'cargo deb'. For other release binaries, we (currently) call 'strip'
# explicitly in the release process.
[profile.deb]
inherits = "release"
debug = false

[package.metadata.deb]
section = "utils"
assets = [
    [
        "target/release/cargonode",
        "usr/bin/",
        "755",
    ],
    [
        "LICENSE-MIT",
        "usr/share/doc/cargonode/",
        "644",
    ],
    [
        "LICENSE-APACHE",
        "usr/share/doc/cargonode/",
        "644",
    ],
    [
        "CHANGELOG.md",
        "usr/share/doc/cargonode/CHANGELOG",
        "644",
    ],
    [
        "README.md",
        "usr/share/doc/cargonode/README",
        "644",
    ],
]
