name: Changelog Management

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install git-cliff
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cargo/bin/git-cliff
          key: ${{ runner.os }}-git-cliff-binary
      
      - name: Install git-cliff if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install git-cliff
        
      - name: Generate Changelog
        run: |
          git-cliff --output CHANGELOG.md
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code CHANGELOG.md || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'docs: update changelog'
          title: 'docs: update changelog'
          body: |
            This PR updates the CHANGELOG.md file based on recent commits.
            
            This is an automated process triggered by git-cliff.
          branch: update-changelog
          delete-branch: true
          labels: documentation
          
      - name: Update PR Description
        if: github.event_name == 'pull_request' && steps.git-check.outputs.changes == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          CHANGELOG_PREVIEW=$(git cliff --unreleased)
          gh pr edit $PR_NUMBER --body "## Changelog Preview
          
          \`\`\`markdown
          $CHANGELOG_PREVIEW
          \`\`\`
          
          $(gh pr view $PR_NUMBER --json body -q .body)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 