name: 🧪 ci installation

on:
  push:
    paths:
      - "install_cargonode.sh"
      - ".github/workflows/ci_installation.yml"
  pull_request:
    paths:
      - "install_cargonode.sh"
      - ".github/workflows/ci_installation.yml"
  workflow_dispatch:

jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Show environment details
        run: |
          uname -a
          echo "OS: ${{ runner.os }}"

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg zip curl unzip

      - name: Install cargonode
        run: |
          chmod +x ./install_cargonode.sh
          ./install_cargonode.sh --verbose --force

      - name: Verify installation
        run: |
          cargonode --version
